### ISSUE TITLE
how to sort the usblist

### ISSUE THREAD

**Issue by NullYing** [Gikoskos/usb.ids_list_in_C#2]
I make the find-test, and it's show

error: UsbList is unsorted

so, how to sort the usblist

**Comment by Gikoskos** [comment]
The error must be somewhere else because the list in this repo is already sorted, you don't have to do any sorting yourself. Did you fix it?

**Comment by NullYing** [comment]
Because I updated the usb.ids list and I remove that error line. it work now.

The program still can't be used to the newest usb.ids list, some line was parser error

**Comment by Gikoskos** [comment]
Yeah the old parser was messed up and didn't work properly. Since the usb.ids list is easy to parse i wrote a much better and more stable one in python 3. You can check it out in the repo. It produces a source file with a UsbDevStruct struct with the current usb.ids, and the search functions

**Comment by NullYing** [comment]
Thanks
